function withOpacity(variableName) {
  return ({ opacityValue }) => {
    if (opacityValue !== undefined) {
      return `rgb(var(${variableName}) / ${opacityValue})`;
    }
    return `rgb(var(${variableName}))`;
  };
}

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#93000b',
        surface: withOpacity('--color-surface'),
        'on-primary': withOpacity('--color-on-primary'),
        'tertiary-container': '#4059aa',
        'surface-container-lowest': withOpacity('--color-surface-lowest'),
        'tertiary-fixed': '#dce1ff',
        'on-primary-fixed': '#410002',
        'inverse-surface': '#4c2700',
        'surface-variant': withOpacity('--color-surface-variant'),
        'on-tertiary-fixed-variant': '#264191',
        'surface-tint': '#b91c1c',
        'primary-fixed-dim': '#ffb4ab',
        'secondary-container': withOpacity('--color-secondary-container'),
        'inverse-on-surface': '#ffeee2',
        outline: withOpacity('--color-outline'),
        'surface-container-low': withOpacity('--color-surface-low'),
        'on-secondary-container': withOpacity('--color-on-secondary-container'),
        'on-tertiary-fixed': '#00164e',
        secondary: withOpacity('--color-secondary'),
        'secondary-fixed': '#ffddb8',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-highest': withOpacity('--color-surface-highest'),
        'on-secondary-fixed': '#2a1700',
        'on-surface': withOpacity('--color-on-surface'),
        'surface-container-high': withOpacity('--color-surface-high'),
        'primary-fixed': '#ffdad6',
        'outline-variant': withOpacity('--color-outline-variant'),
        'on-error-container': '#93000a',
        'on-surface-variant': withOpacity('--color-on-surface-variant'),
        'on-background': withOpacity('--color-on-surface'),
        'on-secondary-fixed-variant': '#653e00',
        error: '#ba1a1a',
        'surface-dim': '#ffd1ac',
        'on-primary-container': '#ffcdc7',
        'secondary-fixed-dim': '#ffb95f',
        background: withOpacity('--color-surface'),
        'on-secondary': '#ffffff',
        'inverse-primary': '#ffb4ab',
        'primary-container': withOpacity('--color-primary-container'),
        'surface-container': withOpacity('--color-surface-container'),
        tertiary: '#264191',
        'surface-bright': withOpacity('--color-surface'),
        primary: withOpacity('--color-primary'),
        'tertiary-fixed-dim': '#b6c4ff',
        'on-tertiary-container': '#cdd6ff',
        chai: withOpacity('--color-chai'),
        kumkum: withOpacity('--color-kumkum'),
        haladi: withOpacity('--color-haladi'),
        indigo: withOpacity('--color-indigo'),
        // Backward-compatible aliases for hand-written app chrome that predates
        // the exact Stitch M3 token names above (same hex values, shorter names).
        ink: withOpacity('--color-on-surface'),
        'ink-variant': withOpacity('--color-on-surface-variant'),
        'primary-on': withOpacity('--color-on-primary'),
        'primary-on-container': '#ffcdc7',
        'secondary-on-container': withOpacity('--color-on-secondary-container'),
        'tertiary-on-container': '#cdd6ff',
        'surface-lowest': withOpacity('--color-surface-lowest'),
        'surface-low': withOpacity('--color-surface-low'),
        'surface-high': withOpacity('--color-surface-high'),
        'surface-highest': withOpacity('--color-surface-highest'),
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        // Note: unlike DEFAULT/lg/xl above, 'full' is intentionally left at
        // Tailwind's built-in 9999px (not overridden to the Stitch config's
        // literal 0.75rem) so avatars, pills and dots stay perfectly round
        // as shown in the mockup screenshots rather than merely rounded-square.
      },
      spacing: {
        'space-lg': '1.5rem',
        'margin-mobile': '1rem',
        margin: '2rem',
        'space-xl': '2rem',
        'space-md': '1rem',
        'gutter-mobile': '0.5rem',
        'space-xs': '0.25rem',
        gutter: '1rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'label-sm': ['Space Grotesk', 'system-ui', 'sans-serif'],
        'body-md': ['Literata', 'Georgia', 'serif'],
        'body-lg': ['Literata', 'Georgia', 'serif'],
        'headline-sm': ['Epilogue', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Epilogue', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Epilogue', 'system-ui', 'sans-serif'],
        'headline-lg': ['Epilogue', 'system-ui', 'sans-serif'],
        'title-md': ['Literata', 'Georgia', 'serif'],
        'label-md': ['Space Grotesk', 'system-ui', 'sans-serif'],
        'display-lg': ['Epilogue', 'system-ui', 'sans-serif'],
        'headline-md': ['Epilogue', 'system-ui', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'system-ui', 'sans-serif'],
        'body-sm': ['Literata', 'Georgia', 'serif'],
        'title-lg': ['Literata', 'Georgia', 'serif'],
        hand: ['Caveat', 'Patrick Hand', 'cursive'],
        chalk: ['Kalam', 'cursive'],
        mono: ['JetBrains Mono', 'monospace'],
        body: ['Literata', 'Georgia', 'serif'],
        display: ['Epilogue', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      keyframes: {
        wobble: {
          '0%, 100%': { transform: 'rotate(-1deg)' },
          '50%': { transform: 'rotate(1deg)' },
        },
        'petal-fall': {
          '0%': { transform: 'translateY(-10vh) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(110vh) rotate(360deg)', opacity: '0' },
        },
      },
      animation: {
        wobble: 'wobble 6s ease-in-out infinite',
        'petal-fall': 'petal-fall 4s linear forwards',
      },
    },
  },
  plugins: [],
};
